<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePRODUCTTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('PRODUCT', function (Blueprint $table) {
            $table->increments('productId');
            $table->integer('categoryId');
            $table->string('name', 100);
            $table->string('description', 1000)->nullable();
            $table->integer('brandId')->nullable();
            $table->integer('sizeId')->nullable();
            $table->tinyInteger('isPackage');
            $table->integer('quantity')->nullable();
            $table->double('weight')->nullable();
            $table->integer('unityId')->nullable();
            $table->binary('icon')->nullable();
            $table->integer('colorId')->nullable();
            $table->tinyInteger('active');
            $table->dateTime('startDate');
            $table->dateTime('endDate');

            $table->index('categoryId', 'fk_product_catalog_category_idx');
            $table->index('sizeId', 'fk_product_catalog_size_idx');
            $table->index('unityId', 'fk_product_catalog_unity_idx');
            $table->index('brandId', 'fk_product_catalog_brand_idx');
            $table->index('colorId', 'fk_product_color_idx');

            $table->foreign('brandId', 'fk_product_catalog_brand')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('categoryId', 'fk_product_catalog_category')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('sizeId', 'fk_product_catalog_size')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('unityId', 'fk_product_catalog_unity')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('colorId', 'fk_product_color')->references('colorId')->on('CNF_COLOR')->onDelete('NO ACTION
')->onUpdate('NO ACTION');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('PRODUCT');
    }
}
