<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSCORETable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('SCORE', function (Blueprint $table) {
            $table->increments('scoreId');
            $table->integer('scoreTypeId');
            $table->integer('userId');
            $table->tinyInteger('state');

            $table->index('scoreTypeId', 'fk_score_catalog_score_type_idx');
            $table->index('userId', 'fk_score_user_idx');

            $table->foreign('scoreTypeId', 'fk_score_catalog_score_type')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('userId', 'fk_score_user')->references('userId')->on('USER')->onDelete('NO ACTION
')->onUpdate('NO ACTION');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('SCORE');
    }
}
