<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateITEMTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ITEM', function (Blueprint $table) {
            $table->increments('itemId');
            $table->integer('listId');
            $table->integer('priorityId');
            $table->integer('quantity');
            $table->integer('unitId');
            $table->string('note', 100)->nullable();
            $table->integer('stateId');

            $table->index('listId', 'fk_item_list_idx');
            $table->index('priorityId', 'fk_item_catalog_priority_idx');
            $table->index('unitId', 'fk_item_catalog_unit_idx');
            $table->index('stateId', 'fk_item_catalog_state_idx');

            $table->foreign('priorityId', 'fk_item_catalog_priority')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('stateId', 'fk_item_catalog_state')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('unitId', 'fk_item_catalog_unit')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('listId', 'fk_item_list')->references('listId')->on('LIST')->onDelete('NO ACTION
')->onUpdate('NO ACTION');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ITEM');
    }
}
