<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMALLTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('MALL', function (Blueprint $table) {
            $table->increments('mallId');
            $table->integer('mallMasterId')->nullable();
            $table->string('name', 100);
            $table->string('description', 1000)->nullable();
            $table->binary('icon')->nullable();
            $table->tinyInteger('active');
            $table->dateTime('startDate')->nullable();
            $table->dateTime('endDate')->nullable();

            $table->index('mallMasterId', 'fk_mall_mall_idx');

            $table->foreign('mallMasterId', 'fk_mall_mall')->references('mallId')->on('MALL')->onDelete('NO ACTION
')->onUpdate('NO ACTION');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('MALL');
    }
}
