<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMALLADDRESSTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('MALL_ADDRESS', function (Blueprint $table) {
            $table->increments('addressId');
            $table->integer('countryId');
            $table->integer('mallId');
            $table->double('latitude');
            $table->double('longitute');
            $table->integer('addressTypeId')->nullable();
            $table->tinyInteger('active');
            $table->dateTime('startDate');
            $table->dateTime('endDate');

            $table->index('countryId', 'fk_address_country_idx');
            $table->index('addressTypeId', 'fk_address_catalog_idx');
            $table->index('mallId', 'fk_address_mall_idx');

            $table->foreign('addressTypeId', 'fk_address_catalog')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('countryId', 'fk_address_country')->references('countryId')->on('CNF_COUNTRY')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('mallId', 'fk_address_mall')->references('mallId')->on('MALL')->onDelete('NO ACTION
')->onUpdate('NO ACTION');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('MALL_ADDRESS');
    }
}
