<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUSERSETTINGTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('USER_SETTING', function (Blueprint $table) {
            $table->increments('userSettingId');
            $table->integer('userId');
            $table->integer('languageId');
            $table->tinyInteger('isNotification');

            $table->index('userId', 'fk_user_setting_user_idx');
            $table->index('languageId', 'fk_user_setting_catalog_language_idx');

            $table->foreign('languageId', 'fk_user_setting_catalog_language')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');
            $table->foreign('userId', 'fk_user_setting_user')->references('userId')->on('USER')->onDelete('NO ACTION
')->onUpdate('NO ACTION');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('USER_SETTING');
    }
}
