<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateLISTTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('LIST', function (Blueprint $table) {
            $table->increments('listId');
            $table->integer('userId');
            $table->string('name', 100);
            $table->dateTime('scheduleDate')->nullable();
            $table->tinyInteger('state');

            $table->index('userId', 'fk_list_user_idx');

            $table->foreign('userId', 'fk_list_user')->references('userId')->on('USER')->onDelete('NO ACTION
')->onUpdate('NO ACTION');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('LIST');
    }
}
