<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCNFLANGUAGETable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('CNF_LANGUAGE', function (Blueprint $table) {
            $table->increments('languageId');
            $table->string('name', 100);
            $table->tinyInteger('active');
            $table->dateTime('startDate');
            $table->dateTime('endDate');

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('CNF_LANGUAGE');
    }
}
