<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCNFCOUNTRYTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('CNF_COUNTRY', function (Blueprint $table) {
            $table->increments('countryId');
            $table->string('name', 100);
            $table->string('isoAlpha2Code', 2);
            $table->string('isoAlpha3Code', 3);
            $table->string('isoNumericCode', 5);
            $table->string('currency', 100)->nullable();
            $table->string('currencySing', 10);
            $table->integer('cnfLanguageId');
            $table->tinyInteger('active');
            $table->dateTime('startDate');
            $table->dateTime('endDate');

            $table->index('cnfLanguageId', 'fk_country_language_idx');

            $table->foreign('cnfLanguageId', 'fk_country_language')->references('languageId')->on('CNF_LANGUAGE')->onDelete('NO ACTION
')->onUpdate('NO ACTION');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('CNF_COUNTRY');
    }
}
