<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCNFCOLORTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('CNF_COLOR', function (Blueprint $table) {
            $table->increments('colorId');
            $table->string('name', 100);
            $table->tinyInteger('isBasic');
            $table->string('hexCode', 7);
            $table->integer('rgbRed')->nullable();
            $table->integer('rgbGreen')->nullable();
            $table->integer('rgbBlue')->nullable();
            $table->string('hslHue', 10)->nullable();
            $table->string('hslSat', 10)->nullable();
            $table->string('hslLum', 10)->nullable();
            $table->tinyInteger('active');
            $table->dateTime('startDate');
            $table->dateTime('endDate');

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('CNF_COLOR');
    }
}
