<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCNFCATALOGTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('CNF_CATALOG', function (Blueprint $table) {
            $table->increments('catalogId');
            $table->integer('catalogTypeId')->nullable();
            $table->string('name', 100);
            $table->string('description', 1000);
            $table->tinyInteger('active');
            $table->dateTime('startDate');
            $table->dateTime('endDate');

            $table->index('catalogTypeId', 'fk_catalog_catalog_idx');

            $table->foreign('catalogTypeId', 'fk_catalog_catalog')->references('catalogId')->on('CNF_CATALOG')->onDelete('NO ACTION
')->onUpdate('NO ACTION');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('CNF_CATALOG');
    }
}
